### ISSUE TITLE
Embedded library cannot be found

### ISSUE THREAD

**Issue by percula** [mongodb/stitch-examples#81]
For the android-mobile todo example, I am experiencing the following exception upon build (without changing anything):

```
2018-12-20 10:35:01.605 5705-5705/com.mongodb.stitch.sdk.examples.todo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mongodb.stitch.sdk.examples.todo, PID: 5705
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mongodb.stitch.sdk.examples.todo/com.mongodb.stitch.sdk.examples.todo.MainActivity}: com.mongodb.embedded.client.MongoClientEmbeddedException: The mongo embedded library could not be initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.mongodb.embedded.client.MongoClientEmbeddedException: The mongo embedded library could not be initialized
        at com.mongodb.embedded.client.MongoClients.init(MongoClients.java:49)
        at com.mongodb.stitch.android.services.mongodb.local.internal.AndroidEmbeddedMongoClientFactory.<init>(AndroidEmbeddedMongoClientFactory.java:33)
        at com.mongodb.stitch.android.services.mongodb.local.internal.AndroidEmbeddedMongoClientFactory.getInstance(AndroidEmbeddedMongoClientFactory.java:41)
        at com.mongodb.stitch.android.services.mongodb.local.LocalMongoDbService$1.getClient(LocalMongoDbService.java:53)
        at com.mongodb.stitch.android.services.mongodb.local.LocalMongoDbService$1.getClient(LocalMongoDbService.java:44)
        at com.mongodb.stitch.android.core.internal.StitchAppClientImpl.getServiceClient(StitchAppClientImpl.java:110)
        at com.mongodb.stitch.sdk.examples.todo.MainActivity.onCreate(MainActivity.java:87)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: com.mongodb.embedded.capi.MongoEmbeddedCAPIException: Unable to load the Mongo Embedded Library.
    Please either: Set the libraryPath when calling MongoEmbeddedCAPI.create or 
    Ensure the library is set on the jna.library.path or the java.library.path system property.
        at com.mongodb.embedded.capi.MongoEmbeddedCAPI.create(MongoEmbeddedCAPI.java:87)
        at com.mongodb.embedded.client.MongoClients.init(MongoClients.java:46)
        	... 21 more
     Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'mongo_embedded': Native library (android-x86/libmongo_embedded.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
        at com.sun.jna.Native.register(Native.java:1647)
        at com.mongodb.embedded.capi.internal.CAPI.<clinit>(CAPI.java:164)
        at com.mongodb.embedded.capi.MongoEmbeddedCAPI.create(MongoEmbeddedCAPI.java:84)
        	... 22 more
```

**Comment by YovoManolov** [comment]
Hi my friend, have you found an answer for your problem, I've encountered the same one ?

**Comment by percula** [comment]
@YovoManolov , I believe it is because we need to initialize the app client. See this other issue I created: https://github.com/mongodb/stitch-android-sdk/issues/85#issuecomment-449146792

Unfortunately I haven't had time to test this yet.

**Comment by mdg-2018** [comment]
Just in case anyone comes across this in the future, the issue here is likely that the Android emulator that you're using is set to x86 rather than x86_64. I ran into this issue and after changing the emulator settings it worked fine.

Docs here: https://docs.mongodb.com/stitch/mongodb/mobile/getting-started/
