### ISSUE TITLE
Error Domain=realm::app::ServiceError Code=14 "TypeError: Cannot access member 'post' of undefined

### ISSUE THREAD

**Issue by selcukyucel** [mongodb/stitch-examples#99]
Hi I am getting an error  at Realm functions,
Calling from iOS app.
`app.functions.token([]) { result, error in
            print(error)
            print(result)
    }`

**Error Domain=realm::app::ServiceError Code=14 "TypeError: Cannot access member 'post' of undefined"**

`exports = function() {
    return context.https.post({
        
        url: "https://apiuat.test.blabla-payments.com/token",
        headers: {
            "Content-Type":"application/x-www-form-urlencoded"
        //"Cookie":"d944fa525886d228904d507202154efa=d9e464068b828f7908d934beed4bd7c9; TS012f2652=01ad890da991078df75e3f20a99b772ed008d580c232a9fb392522a704402c550596b532540c8c3526a8f1f4f997e111e01468c4800e7ae828508cac14bf16a90782d05878"
        },
        body: { merchantId:906933
            ,password:"u16q9rZ02bW0jqTjxH8t"
            ,allowOriginUrl:null
            ,timestamp:Date.now()
            ,action:"PURCHASE"
            ,customerId:"sample-0002"
            ,amount:25.00
            ,currency:"EUR"
            ,country:"IE"
            ,language:"en"
            ,customerFirstName:"selcuk"
            ,customerLastName:"yucel"
            ,merchantNotificationUrl:"https://ptsv2.com/t/post" },
            
            encodeBodyAsJSON: true
            
        })
        .then(response => {
            // The response body is encoded as raw BSON.Binary. Parse it to JSON.
            const ejson_body = EJSON.parse(response.body.text());
            console.log("Result: ",ejson_body)
            return ejson_body;
        })
    };`

**ERROR**

TypeError: Cannot access member 'post' of undefined
> trace: 
TypeError: Cannot access member 'post' of undefined
    at exports (token.js:4:12)
    at apply (<native code>)
    at token_wrapper.js:2:5
    at execute (<native code>)
    at apply (<native code>)
    at <anonymous>:16:10
    at <anonymous>:12:1

**Comment by selcukyucel** [comment]
Problem solved.
